### PR TITLE
VCB-1 User Interface

### PR DESCRIPTION
**Pull request by clooudch**
This PR contains a major upgrade for the user interface and includes:

major changes:
- an improved responsive layout for the app using a css grid
   - depending on the screen size the board is either placed on the right side or it shares the same space as the editor. the app component allows switching between 'editor' and 'board' when they share the same space
   - the 'editor' component had to be split into a 'controls' and an 'editor' component
     - the 'controls' component has a reference to the 'editor' component, so that it can 'getCode', 'showError' and 'highlightStep'
     - 'editor' component has now separate compartments for different types of highlighting. this way error highlighting is independent of step highlighting
 - errors are now shown in the 'editor' component below the code mirror editor. when an error messages is shown , there is no layout jump happening, instead the code mirror editor shrinks accordingly.
 -  responsive sizing of most user interface elements. rem is used instead of pixels and root font size is changed depending on screen size to scale the user interface to the device
- an improved responsive design for the CT board
  - the board sizing should match more or less the actual CT board
  - the board has a fixed aspect ration and fills the whole available space (but has a minimal size)
  - the components on the board are placed using absolute positioning using percentages, so that they can be resized
  - colors have been matched to the actual CT board
- a title header with the content 'Virtual CT-Board'
- memory component has been completely redesigned
  - the memory content is now displayed as bytes and not words
- registers and flags component was merged into one component to allow for easier layouting
- 'help' and 'search memory' is now displayed as a popover
- memory and register component are now event emitters of a 'change' event
  - UI updates are therefor now attached to 'change' and 'afterCycle' event has been removed
  - event emitter can forward events to another instance. this is used for the memory bus which forwards events from the individual devices or for the device which forwards events from the inner memory instance
- lcd device went through a major refactoring to improve code readability

minor changes:
- use 'classNames' utility for dynamic class names in react
- all components have now a root element called 'x-component'
- containers for components are called 'x-component-container'
- all css style rules for components start with '.x-component', so that they are better isolated
- devices have been renamed to have suffix 'Device' for consistency and avoiding naming conflicts
- switches have been renamed to 'dip-switches' to avoid confusion (same naming used in CT board documentation)
- rotary switch has been renamed to 'hex-switch' to avoid confusion (same naming used in CT board documentation)
- '7seg' / 'sevenSeg' has been renamed to 'SevenSegment' on all occurrences to make it more consistent
- processor cycle speed has been increased to '10ms'

fixes:
- 'ParseError' wrongly incremented the line. there is also a dedicated bug for this.
- missing 'key' attributes are added to for loops in react components

### CODE REVIEW

**Comment by deflox** [comment]
@clooudch There are still merge conflicts. I guess we should first fix them before I start to review.

**Comment by clooudch** [comment]
> @clooudch There are still merge conflicts. I guess you should first fix them before I start to review. And the build is also still failing.

I fixed now the current merge conflicts. I guess we should wait for #43 and #41 to be merged first. Then I will fix the additional merge conflicts and after that we can merge this PR.

**Comment by deflox** [comment]
Merged #41

**Comment by clooudch** [comment]
Now PR #43 is merged as well and I have merged back all changes from current master.

**Review by deflox — COMMENTED** [review]
Overall looks good. My only suggestion would be that we do not clear the error message in case the user types something as discussed, but in my opinion we should clear the highlighting, because if the user makes an edit the result is something like this, which does not make much sense in my opinion and looks a bit odd:

image

**Comment by clooudch** [comment]
> Overall looks good. My only suggestion would be that we do not clear the error message in case the user types something as discussed, but in my opinion we should clear the highlighting, because if the user makes an edit the result is something like this, which does not make much sense in my opinion and looks a bit odd:
> 
> image

I will try to automatically re-assemble the executable as the user types code (maybe with a delay) and let's see how it behaves.

**Comment by clooudch** [comment]
The seven segment is now merged into this branch and updated to have responsive styling.

**Comment by deflox** [comment]
Ok I played around with the seven segment display a bit and looks good. The rest was already reviewed.

**Comment by clooudch** [comment]
> > Overall looks good. My only suggestion would be that we do not clear the error message in case the user types something as discussed, but in my opinion we should clear the highlighting, because if the user makes an edit the result is something like this, which does not make much sense in my opinion and looks a bit odd:
> > image
> 
> I will try to automatically re-assemble the executable as the user types code (maybe with a delay) and let's see how it behaves.

I did some testing and I think clearing the error every time the user inputs a change, is the best approach. I tried to automatically re-assemble and check if the error is still present, but this was not much better and had the additional drawbacks that performance was worse and the runtime error behavior was weird.

The error now disappears when the user changes the content of the code editor.

**Comment by clooudch** [comment]
From my side this PR can now be merged. I just integrated the latest version of the master.

**Review by deflox — APPROVED** [review]

**Pull request merged**
