### PR TITLE
VCB-2 RegisterInformation

### PR DESCRIPTION
**Pull request by clooudch**

### CODE REVIEW

**Review by deflox — APPROVED** [review]
Looks good to me. `npm run test` runs fine on my machine and the build too.

**Comment by deflox** [comment]
The only thing we could maybe fix in this branch is the security vulnerability that is currently being reported by npm.

**Comment by m-dot-wigger** [comment]
Should we use this PR to verify the build pipeline process?

@clooudch Is it intended that there is no merge commit of current master?

**Comment by clooudch** [comment]
> The only thing we could maybe fix in this branch is the security vulnerability that is currently being reported by npm.

Has been fixed by dependabot.

**Comment by clooudch** [comment]
> Should we use this PR to verify the build pipeline process?

Yes. We should merge the build pipeline PR first and then merge this.

> @clooudch Is it intended that there is no merge commit of current master?

Wo do not need a merge back from master. The PR is probably mergeable without this. Because there are not a lot of conflicts. And also there was a merge back recently.

**Review by m-dot-wigger — APPROVED** [review]
Acceptance criterias are met

**Pull request merged**
