### PR TITLE
vcb-71 crossplatform dev

### PR DESCRIPTION
**Pull request by m-dot-wigger**
#71 (https://virtualctboard.atlassian.net/browse/VCB-71)

### CODE REVIEW

**Comment by m-dot-wigger** [comment]
not sure if should force ts and tsx files to just lf?

**Comment by deflox** [comment]
When I run prettier on all files I still get changes detected when running `git status`. I guess that the issue is that prettier for whatever reason replaces CRLF with LF when formatting the files. And I think this settings will not help since they just tell git that text files should always be stored as LF in the staging area and within commit and should be converted back to CRLF when files are checked out on Windows. But since prettier explicitly replaces CRLF with LF when formatting, git detects this as "change" but these changes will then vanish as soon as they are added to the staging area because there the files are anyways stored as LF. 

So I think we probably need to either tell prettier to preserve line endings when formatting or agree in the team that everyone works with LF in their code editors so we never need convertion in the first place.

I would probably add also ".json, .html, .css, .assembly" file extensions.

**Comment by clooudch** [comment]
I think the main issue here is that the 'checked out' version of the source code (controlled by core.autocrlf) does not match the settings in prettier (right now EOF=LF).

I would propose to:
- set 'prettier' to EOF='auto'
- enforce LF when storing in repository (can be done with .gitattributes)

This way we would have always LF in repository (because of .gitattributes), but the user can decide how they want to work locally (according to their core.autocrlf setting). Prettier would then not enforce a certain EOF style, but this is not necessary as git takes care of this.

**Review by deflox — APPROVED** [review]
Looks good now. I checked out a fresh copy of the repo and ran pretter with `npm run format-all-files` and it did not change `CRLF` to `LF` so git did not detect any changes.

**Comment by m-dot-wigger** [comment]
description of property for prettier: https://prettier.io/docs/en/options.html#end-of-line

**Comment by deflox** [comment]
Maybe we could also change the readme to include the command `npm run format-all-files` instead of `npx prettier --write .` which can be used by everyone to easily format all files before committing.

**Review by clooudch — APPROVED** [review]

**Pull request merged**
