### PR TITLE
Vcb 16 execute code

### PR DESCRIPTION
**Pull request by deflox**
There are three different states the code editor can be in. I placed some documentation and a diagram about the states into the /docs folder. The entered code should now be assembled and loaded onto the CT board. But there are still errors when the code is executed because the `writeObjectFile()` in the `Flash` device is not yet implemented so the object file cannot be read from the start address of the Flash device. I'm not really sure if this is in the scope of this story? Or is this just a bug that needs to be fixed first?

When an error occurs during assembling the code, the error is just displayed for two seconds as an alert over the code editor. This is probably not the optimal solution. I guess later we could show the error message directly at the line where the problem is happening, but since not much meaningful is returned by the assembler function yet, this solution is good enough in my opinion.

### CODE REVIEW

**Comment by clooudch** [comment]
I would say that the `writeObjectFile` is scope of this story. Because the story acceptance criteria can not be fulfilled without this.

**Comment by deflox** [comment]
> I would say that the `writeObjectFile` is scope of this story. Because the story acceptance criteria can not be fulfilled without this. I can create a task and implement it, if you want.

Yeah would be fine for me!

**Comment by clooudch** [comment]
> > I would say that the `writeObjectFile` is scope of this story. Because the story acceptance criteria can not be fulfilled without this. I can create a task and implement it, if you want.
> 
> Yeah would be fine for me!

I have created a task: https://virtualctboard.atlassian.net/browse/VCB-79

**Review by clooudch — APPROVED** [review]

**Comment by deflox** [comment]
Also I am wondering why our pipeline is not also reporting a test failure? Either I'm doing something wrong locally (I did run `git pull`, `npm install` and `npm run test` though) or the pipeline is not correct...

**Comment by deflox** [comment]
> > Also I am wondering why our pipeline is not also reporting a test failure? Either I'm doing something wrong locally (I did run `git pull`, `npm install` and `npm run test` though) or the pipeline is not correct...
> 
> The test also failed on my machine. The test failed because a typescript issue. Maybe the test run in the pipeline does not report such issues?
> 
> Anyways, I fixed the test.

I have created a new bug for this: https://virtualctboard.atlassian.net/browse/VCB-94 I will take it up with Raphel.

I guess the PR is fine now. I cannot approve myself because I'm the author of the PR... :)

**Pull request merged**
